### ISSUE TITLE
Testing fdcPlot

### ISSUE THREAD

**Issue by BTDangelo** [kbrannan/ldcpackage#10]
How do I test the fdcPlot script to make sure it works? 

Specifically, for the "fdcPlot function", what do I enter for the "flow.exceed" input? I understand this is the flow exceedance values, and "flow.exceed" is a function that calculates these values.

**Comment by kbrannan** [comment]
check the help in the heading of flow exceed function for the input. let me know if that answers your questions

**Comment by BTDangelo** [comment]
From looking at the heading of the flow exceed function it seems that my flow.exceed input would be tmp.exceed, since this is the flow exceed values returned from the function so testing the function I would assume to input

flow.exceed = tmp.exceed

The only other way that it would make sense for me to write this is 

flow.exceed = flow.exceed   - This may not work though since the parameter and function have the same 
                                                name

**Comment by kbrannan** [comment]
I think using "tmp.exceed" as the parameter name within your function is a good work around.

**Comment by BTDangelo** [comment]
So this means I would want to change the first parameter that was "flow.exceed" to "tmp.exceed"? And then run the function as so, "tmp.exceed = flow.exceed" ?

fdc.ss.est.flow.plot <- function(tmp.exceed=NULL,       *****CHANGE THIS PARAMETER ??***
                                                 flow.est=NULL,
                                                 ss.est=NULL,
                                                 plot.fn=NULL,
                                                 y.lims=NULL) {

**Comment by BTDangelo** [comment]
Is plot.fn the file path for the fdcPlot to be saved in? And if so when testing, can I define plot.fn as the filepath where I want the saved plot to be placed by typing the following 

fdc.plot.figure <- //deqhq1/Figures

**Comment by kbrannan** [comment]
Yes and Yes
The network path in your question (//deqhq1/Figures) may not work. In file explorer, check the network path of the folder you want to write to. I think the path you would use will have "mid-coast" in it.

**Comment by BTDangelo** [comment]
I keep getting an error as follows

cannot open file '//deqhq1/TMDL/TMDL_WR/Models/Bacteria/LDC/Bernadette-workspace/Figures'

**Comment by kbrannan** [comment]
Did you create a branch and push your work to GitHub? When you do that, I could look directly at your code to help debug it.

**Comment by BTDangelo** [comment]
I created a branch called fdcPlotTest

I keep coming up with the same error. When I define plot.fn = Null it does produce a plot. But I am not sure if this plot is what we are looking for.

**Comment by kbrannan** [comment]
The error maybe in the path you used. Try this:
'//deqhq1/tmdl/TMDL_WR/MidCoast/Models/Bacteria/LDC/Bernadette-workspace/figures'

**Comment by BTDangelo** [comment]
I tried the path you just posted, it still comes up with an error. 
Is there something in the code that would need to change?

**Comment by kbrannan** [comment]
I think I found the problem in the  test script

check the edits I made in the file: fdcPlotTest.R

it is in the latest commit on github

**Comment by BTDangelo** [comment]
That fixed that issue. 

There is now a different issue that comes up, this is what I have entered for my parameters, the resulting error is shown below.

fdc.ss.est.flow.plot(flow.exceed=tmp.exceed(v.flow),
                     flow.est=df.flow$flow,
                     ss.est=tmp.fdc.ss.estimate(),
                     plot.fn=fdc.plot.figure,
                     y.lims=y.lim.fdc) 

Error: XML content does not seem to be XML: '//deqhq1/tmdl/TMDL_WR/MidCoast/Data/Bacteria/StreamStatsData/'

**Comment by BTDangelo** [comment]
Is this issue due to "ss.est" being defined as the "fdc.ss.estimate" function?

fdc.ss.estimate <- function(ss.fn=NULL,ss.path="//deqhq1/tmdl/TMDL_WR/MidCoast/Data/Bacteria/StreamStatsData/",
                             Eq.Region=1)
 
 tmp.fdc.ss.estimate <- fdc.ss.estimate

**Comment by kbrannan** [comment]
Yep, file the xml file for your station in the folder and apply the fdc.ss.estimate function to get the data.frame for ss.est

**Comment by BTDangelo** [comment]
I can't seem to find the xml file for my station. I believe you said the test data you gave me was from station 11474. Is that correct? If so where would I find the xml file? I searched in all data files and searched using the search bar as well. Nothing Came up.

**Comment by kbrannan** [comment]
I think it is station 11476

**Comment by BTDangelo** [comment]
OK, so next I did this

tmp.ss.est.fn <- paste0("st",11476,".xml")   
 
fdc.ss.estimate(ss.fn=tmp.ss.est.fn, 
                         ss.path="//deqhq1/tmdl/TMDL_WR/MidCoast/Data/Bacteria/StreamStatsData/",
                         Eq.Region=1)

It seemed to work. Does that make sense to do?

**Comment by kbrannan** [comment]
Yep, that should give the information needed to make the fdc plot

**Comment by BTDangelo** [comment]
fdc.ss.est.flow.plot(flow.exceed=tmp.exceed(v.flow),
                     flow.est=df.flow$flow,
                     ss.est=fdc.ss.estimate(),     **<---------- Is this how you could define this variable? Or do I 
                                                                                  need to enter something into the parenthesis?**
                     plot.fn=fdc.plot.figure,
                     y.lims=y.lim.fdc)

**Comment by BTDangelo** [comment]
I also tried this

 ss.est=fdc.ss.estimate(ss.fn=tmp.ss.est.fn, 
                                    ss.path="//deqhq1/tmdl/TMDL_WR/MidCoast/Data/Bacteria/StreamStatsData/",
                                    Eq.Region=1),

**Comment by BTDangelo** [comment]
I ran the fdc.ss.estimate function from the "LDC Functions.R" script. Then I ran my function as so

fdc.ss.est.flow.plot(flow.exceed=tmp.exceed(v.flow),
                     flow.est=df.flow$flow,
                     ss.est=fdc.ss.estimate(ss.fn=tmp.ss.est.fn,
                                       ss.path="//deqhq1/tmdl/TMDL_WR/MidCoast/Data/Bacteria/StreamStatsData/",
                                       Eq.Region=1),
                     plot.fn=fdc.plot.figure,
                     y.lims=y.lim.fdc) 

When doing so there is a plot created and sent to the folder I want it in, but when I go to view the .png file it comes up with "Windows photo viewer can't open this picture because the picture is being edited in another program"

**Comment by kbrannan** [comment]
type command "dev.off()" then try to reopen the png file. This commend closes the connection to the file, which allows other programs to use it.

**Comment by BTDangelo** [comment]
Now for some reason it is not recognizing the xml file 

 Error: XML content does not seem to be XML: '//deqhq1/tmdl/TMDL_WR/MidCoast/Data/Bacteria/StreamStatsData/st11476.xml'

**Comment by BTDangelo** [comment]
I got everything to work except for the same issue viewing the image. I typed "dev.off()" after and still same issue.

**Comment by kbrannan** [comment]
repoet  the command dev.off() until you get and error response. You may have multiple graphic devices open. A graphic devise is opens each time you open a png file to write the graph.

**Comment by BTDangelo** [comment]
Now it comes up with the error that the file is too large or corrupted.

**Comment by BTDangelo** [comment]
When trying to push my changes to my fdcPlotTest.R file this is the message I get in git Shell

Auto-merging ldc/R/fdcPlotTest.R
CONFLICT (content): Merge conflict in ldc/R/fdcPlotTest.R
Automatic merge failed; fix conflicts and then commit the result.

I am not sure how to fix conflicts.

**Comment by kbrannan** [comment]
What branch are you trying to push to?
There are three:
master (you can't push to)
fdcPlotTest
streamstats (a branch I am using)

Make sure you are pushing to the fdcPlotTest branch on GitHub

**Comment by BTDangelo** [comment]
fdcPlotTest is what I am trying to push to 

I have git Shell opened and it shoes my local directory to be fdcPlotTest
I then typed the command "git push" and that is when I get the message
