### ISSUE TITLE
Add more help info to the fdcPlot function

### ISSUE THREAD

**Issue by kbrannan** [kbrannan/ldcpackage#4]
Put the help info in the form used by roxygen in the header of the function file. Take a look at the top of the ldcpackage/ldc/R/ldcPlot.R file to see what we need. You can copy and paste the info form that file and then update for the fdcPlot function

**Comment by BTDangelo** [comment]
I added the documentation to my fdcPlot.R file. I may need to make some adjustments.

**Comment by BTDangelo** [comment]
I added the documentation to my fdcPlot.R file. I may need to make some adjustments and can do so next Monday.

Bernadette

**Comment by kbrannan** [comment]
Let's check this after you push your commits to GitHub next Monday
