### ISSUE TITLE
New flow exceedance function

### ISSUE THREAD

**Issue by kbrannan** [kbrannan/ldcpackage#9]
a created a stand alone function to calculate the flow exceedances for a vector of flows. Please use this functions in places where you need flow exccedance values. Maddee-please replace the intermal function in ldc-functions with the stand alone function.

**Comment by MaddeeRubenson** [comment]
I committed the changes.

**Comment by kbrannan** [comment]
Remember to comment on this issue to let me know when you made your changes, commited, and pushed to your branch. Then you can make a pull request

**Comment by kbrannan** [comment]
function completed, but needs documentation
